---
- name: Set Password
  hosts: test
  user: infrausr
  become: yes
  ignore_errors: yes
  gather_facts: no
  vars:
    - value:
      - { name: 'adminusr', update_pass: 'Reset@123' }
      - { name: 'kamal', update_pass: 'Reset@123' }
      - { name: 'user3', update_pass: 'Reset@123' } 

  tasks:
  - name: Is user on this system?
    action: getent
      database=passwd
    no_log: True

  - name: Reset Password - skips if user not already created
    action: user name={{ item.value.name }} state=present password={{item.value.update_pass}} update_password=always 
    with_dict: users
    when: item.value.name in getent_passwd