- hosts: newhost
  tasks:
  - name: adding several users
    user:
      name={{ item.name }}
      state=present
      comment={{ item.comment }}
      password={{ item.password}}
      home=/home/{{ item.name }}
      shell=/bin/bash
      update_password=on_create
      createhome=yes
    with_items:
      - { name: 'noramlusr', comment: 'normalusr', password: '$1$3Zdze7Vx$GfSfGI5TkePOrzrFCemgw.' }
      - { name: 'adminusr', comment: 'adminusr', password: '$1$3Zdze7Vx$0SFgKzoAwTg5WI1ITShvs1' }
      - { name: 's4admin', comment: 's4admin', password: '$1$3Zdze7Vx$10d2.WLuMzZT/qv1CFVkf0' } 
