- hosts: 10.61.3.77
  tasks:
  - name: Ansible lineinfile multiple lines with_items example
    lineinfile:
      dest: /etc/rsyslog.conf
      insertafter: EOF
      line: '*.* @@10.61.2.222:514'

  - name: Ansible systemd service restart example
    service:
      name: rsyslog
      state: restarted
      enabled: yes
